### ISSUE TITLE
The openalpr python API

### ISSUE THREAD

**Issue by linkkong** [openalpr/train-ocr#23]
When I read the API page   http://doc.openalpr.com/bindings.html#python  ,
the first line 'from openalpr import Alpr' cause a problem 'ImportError: No module named openalpr'.
So I think it need a module named openalpr, but where can I get the module?
Wish you can help me!Thanks！

**Comment by matthill** [comment]
on Ubuntu: sudo apt-get install python-openalpr

**Comment by LyonOconner** [comment]
> on Ubuntu: sudo apt-get install python-openalpr

on windows?
