### ISSUE TITLE
My new country training will be available in Cloud API?

### ISSUE THREAD

**Issue by PierreMarieRiviere** [openalpr/train-ocr#27]
Hi,
I will train openALPR for Cambodia, but I am using the Cloud API in my app. Will my training be available within the Cloud API?

**Comment by matthill** [comment]
If you submit all your training data to the OpenALPR project, we can include it with future software releases.  Otherwise, it will not be available.

**Comment by PierreMarieRiviere** [comment]
How long time should I expect to be waiting from my submission to the integration?

**Comment by PierreMarieRiviere** [comment]
Is it ok to train for one type of vehicle only (say motorcycle) ?

**Comment by matthill** [comment]
It's usually a few months between releases.  training for one plate type is fine.

**Comment by aniethomas** [comment]
hai matt

> It's usually a few months between releases. training for one plate type is fine.

Hi matt, 
 am training for 3lakhs indian number plates.... while training ocr for more characters am getting an error like tiff file size is too large... please help me to get rid of this... and i have generated 2 traineddata for india is there is any possibilities to merge into one
