### ISSUE TITLE
Issue running train.py

### ISSUE THREAD

**Issue by harshmunshi** [openalpr/train-ocr#28]
Hi Matt,  

I am getting the following error, please help :)

Two-Letter Country Code to Train: sr
Processing: ./sr/input/leu.serbia.exp0.box
Executing: /home/harsh/Documents/Number_Plate_Training/tesseract -l eng ./sr/input/leu.serbia.exp0.tif leu.serbia.exp0 nobatch box.train.stderr
sh: 1: /home/harsh/Documents/Number_Plate_Training/tesseract: Permission denied
mv: cannot stat './leu.serbia.exp0.tr': No such file or directory
mv: cannot stat './leu.serbia.exp0.txt': No such file or directory
sh: 1: /home/harsh/Documents/Number_Plate_Training/training/unicharset_extractor: not found
Executing: /home/harsh/Documents/Number_Plate_Training/training/mftraining -F ./tmp/font_properties -U unicharset -O ./tmp/lsr.unicharset ./tmp/*.tr
sh: 1: /home/harsh/Documents/Number_Plate_Training/training/mftraining: not found
rm: cannot remove './unicharset': No such file or directory
mv: cannot stat './tmp/lsr.unicharset': No such file or directory
cp: cannot stat './sr/input/unicharambigs': No such file or directory
sh: 1: /home/harsh/Documents/Number_Plate_Training/training/cntraining: not found
mv: cannot stat './shapetable': No such file or directory
mv: cannot stat './pffmtable': No such file or directory
mv: cannot stat './inttemp': No such file or directory
mv: cannot stat './normproto': No such file or directory
sh: 1: /home/harsh/Documents/Number_Plate_Training/training/combine_tessdata: not found
mv: cannot stat './lsr.unicharset': No such file or directory
mv: cannot stat './lsr.shapetable': No such file or directory
mv: cannot stat './lsr.pffmtable': No such file or directory
mv: cannot stat './lsr.inttemp': No such file or directory
mv: cannot stat './lsr.normproto': No such file or directory
mv: cannot stat './lsr.unicharambigs': No such file or directory

**Comment by ilikecats567** [comment]
Hi, did you solve this problem?

**Comment by harshmunshi** [comment]
I did actually, set the path of the tesseract correctly.

**Comment by stevenbp** [comment]
How, where was your tesseract directory?

**Comment by sezan92** [comment]
Can you clarify the necessary steps?

**Comment by beerjamin** [comment]
Here are the steps for fixing the error. 
The problem is that your tesseract executable is not on the same path as the one on the `train.py` file, you can check it out [here](https://github.com/openalpr/train-ocr/blob/8dd50158334be077a52883af2a567e479fd8fb1c/train.py#L8)
What  you need to do is locate where your tesseract executable is and change the path accordingly
