### ISSUE TITLE
Where is openalpr-utils-prepcharsfortraining ?

### ISSUE THREAD

**Issue by soufianesabiri** [openalpr/train-ocr#47]
I have OpenALPR, Tesseract and OpenCV installed in Windows 10. Where can I find the file openalpr-utils-prepcharsfortraining to create the tif from the character images? Please help! Thanks in advance!

**Comment by soufianesabiri** [comment]
I ended up using openalpr in Ubuntu virtual machine

**Comment by Jortega16** [comment]
hello, how are you, how did you execute this command since I am installing a new plate format and I cannot find how to create the missing files
