### ISSUE TITLE
./train new country code

### ISSUE THREAD

**Issue by lastessa** [openalpr/train-ocr#6]
Hi,
when i try to proceed training, i give follow error.
root@ubuntu:/usr/local/src/train-ocr# ./train.py
Two-Letter Country Code to Train: ua
Processing: ./ua/input/leu.ukraine.exp0.box
Executing: /usr/local/src/tesseract-ocr/api/tesseract -l fra ./ua/input/leu.ukraine.exp0.tif leu.ukraine.exp0 box.train.stderr
Error opening data file /usr/local/src/tesseract-ocr/tessdata/fra.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'fra'
Tesseract couldn't load any languages!
Could not initialize tesseract.
mv: cannot stat ‘./leu.ukraine.exp0.tr’: No such file or directory
mv: cannot stat ‘./leu.ukraine.exp0.txt’: No such file or directory
Extracting unicharset from ./ua/input/leu.ukraine.exp0.box
Wrote unicharset file ./unicharset.
Executing: /usr/local/src/tesseract-ocr/training/mftraining -F ./tmp/font_properties -U unicharset -O ./tmp/lua.unicharset ./tmp/_.tr
Warning: No shape table file present: shapetable
Reading ./tmp/_.tr ...

Error: Unable to open ./tmp/_.tr!
signal_termination_handler:Error:Signal_termination_handler called:Code 3000
Segmentation fault (core dumped)
mv: cannot stat ‘./tmp/lua.unicharset’: No such file or directory
cp: cannot stat ‘./ua/input/unicharambigs’: No such file or directory
Reading ./tmp/_.tr ...

Error: Unable to open ./tmp/*.tr!
signal_termination_handler:Error:Signal_termination_handler called:Code 3000
Segmentation fault (core dumped)
rm: cannot remove ‘./shapetable’: No such file or directory
mv: cannot stat ‘./pffmtable’: No such file or directory
mv: cannot stat ‘./inttemp’: No such file or directory
mv: cannot stat ‘./normproto’: No such file or directory
Combining tessdata files
Error opening unicharset file
Error combining tessdata files into lua.traineddata
mv: cannot stat ‘./lua.unicharset’: No such file or directory
mv: cannot stat ‘./lua.pffmtable’: No such file or directory
mv: cannot stat ‘./lua.inttemp’: No such file or directory
mv: cannot stat ‘./lua.normproto’: No such file or directory
mv: cannot stat ‘./lua.unicharambigs’: No such file or directory

additional info:
echo $TESSDATA_PREFIX
//usr/local/src/openalpr/runtime_data/ocr

root@ubuntu:/usr/local/src/train-ocr/ua/input# ls -la
total 32
drwxr-xr-x 2 root root  4096 Nov  1 21:38 .
drwxr-xr-x 3 root root  4096 Nov  1 21:37 ..
-rw-r--r-- 1 root root  1060 Nov  1 21:38 leu.ukraine.exp0.box
-rw-r--r-- 1 root root 19298 Nov  1 21:38 leu.ukraine.exp0.tif

**Comment by repletetop** [comment]
I get error like this:
Error opening data file /usr/local/src/tesseract-ocr/tessdata/fra.traineddata
So 
Just copy the files from: openalpr/runtime_data/ocr/tessdata to  openalpr/runtime_data/ocr/
It works
