### ISSUE TITLE
GH plates training error 

### ISSUE THREAD

**Issue by khlitoshi** [openalpr/train-ocr#7]
Hi, 
I'm trying to train the ghana plates but I've only 33 plates images.
I'm getting the error below, what is the cause and how to fix it?
Thanks.

![train_error](https://cloud.githubusercontent.com/assets/3183981/6313513/f841b578-b9f2-11e4-86d6-4e73aad0dde8.png)

**Comment by matthill** [comment]
That's the opencv LBP training program.  It's not an error, it's just saying that it's achieved the best possible outcome given the positive sample count.

In this case, 33 samples will not yield a good detector.  You'll need at least a thousand positive images.
