### ISSUE TITLE
Help to train OCR

### ISSUE THREAD

**Issue by Barathlakshmanan** [openalpr/train-ocr#8]
I am training openALPR for Chinese characters. I have problem while training my images, the code accepts only A-Z and 0-9 as inputs, can you guide me how to give Chinese characters as input? I have scim installed to switch between languages but i am not able to do it with this trainer. Any help is appreciated. Thanks in advance.

**Comment by matthill** [comment]
Yes, you're right.  The training program only accepts ASCII keys as inputs.  Tesseract and OpenALPR both support Unicode.  This trainer will need to get updated as well.

**Comment by matthill** [comment]
I've made enhancements to the training workflow when adding support for South Korean license plate OCR.  China should be similar.

I used a TTF font sheet to do the training.  I added some documentation describing this process.

**Comment by ghpass** [comment]
how to train ?

**Comment by ghpass** [comment]
The document is hard for me. I want to train chinese characters. Is there any examples?

**Comment by xiebianhuzi** [comment]
@Barathlakshmanan have you solve the problems, please tell me how to train openalpr for Chinese characters,thank you,or any documentation describing the process?

**Comment by xiebianhuzi** [comment]
@matthill have you maked it?can you tell me the detailed process?thank you.I want to train openALPR for Chinese characters.

**Comment by xiebianhuzi** [comment]
@matthill @Barathlakshmanan I need some help,please,my mailbox is xiebianhuzi@gmail.com,thank you.
