### ISSUE TITLE
tif character spacing

### ISSUE THREAD

**Issue by robertocarvajal** [openalpr/train-ocr#9]
Hi, I'm trying to train ocr for a specific font based on about 200 plates and I noticed the combined.tif file generated had the characters very close to each others causing the trainer program to fail, when I compared to the tif files inside the eu directory I could tell right away that those seem to be generated better, is there a way to set the spacing when generating the tif file? currently I could train with about 130 plates but once I reached 200 plates and my charset increased, tesseract failed on every character and couldn't find any blobs inside the tif file.

**Comment by matthill** [comment]
Thanks, Roberto.  I updated the utility to accept a configurable tile width/height in this commit https://github.com/openalpr/openalpr/commit/06d1a1952e42e4a5e45572d2aa06c6301fa8c2dc
